### ISSUE TITLE
UNTMOD issue

### ISSUE THREAD

**Issue by zzw0812** [nauyan/Segmentation#2]
when I run the Test.py to test the UNTMOD model, I got this error: "ValueError: Unknown layer: BilinearUpSampling2D" , I want to know how to solve this problem? Thanks!

**Comment by nauyan** [comment]
Have you installed all the required libraries present in the requirments.txt file?

**Comment by zzw0812** [comment]
> Have you installed all the required libraries present in the requirments.txt file?

yes, I am sure. By the way, you didn't add the UNTMOD model in the Test.py, so I add it like UNET style in the Test.py, just like this:
if config['Model']=="UNETMOD":
    model = keras.models.load_model("./Results/weights/" + config['Model'] + "/" +config['Model']+"-Best.h5", compile=False)

**Comment by nauyan** [comment]
I have just updated the repo and modifed the Test.py file but you would have to add custom layer of BilinearUpSampling2D while loading weights.

**Comment by zzw0812** [comment]
> I have just updated the repo and modified the Test.py file but you would have to add a custom layer of BilinearUpSampling2D while loading weights.
Thanks for your reply, yes, I have add a custom layer by myself, the code just like [this:](https://github.com/zzw0812/zzw0812.github.io/commit/08b541908886239d19702e65c7f362b376578999), am right?

**Comment by nauyan** [comment]
Yes that is fine.
